### ISSUE TITLE
Process doesn't terminate after its done

### ISSUE THREAD

**Issue by PedroBarcha** [impactcentre/ocrevalUAtion#12]
Hi there!
First of all congratulations for the software, it's the best one I've found around!
So, I've written a script that is supposed to run ocrevalUAtion on several hocr/groundtruth sets. However I've been facing a problem that is the fact that my script stops after the first set is evaluated, because  ocrevalUAtion's process doesn't terminate after it's done. Is there some way to solve this situation?
Thanks in advance!

**Comment by cforcey** [comment]
I am having trouble scripting this command as well to run on a directory of files.  The console log stays open and the System.exit(0) does not end the program until I manually close the window.  Once I manually close the window, the system exits as expected.  But I can't figure out how to prevent that window from opening in the first place.  Many apologies if this is an obvious java question and thanks so much for this wonderful utility!  Charlie

The command I am running:
```
java -cp /Users/cforcey/Dev/ocr_testing/ocrevaluation.jar eu.digitisation.Main -gt ./input/unlv/bus.3A/0/8550_001.3A.txt -ocr ./output/unlv/bus.3A/0/8550_001.3A_tesseract.txt -o ./output/unlv/bus.3A/0/8550_001.3A_ocrevaluation.html -ip -ic -id -c
```
When I run it with " &" at the end, my script continues but I still get a window for each invocation of the command.

<img width="601" alt="screen shot 2018-02-14 at 1 04 59 am" src="https://user-images.githubusercontent.com/38297/36189989-7de2d326-1123-11e8-9ec0-9c3d51660dc2.png">

Thanks so much!  Charlie
