### ISSUE TITLE
Software license is missing

### ISSUE THREAD

**Issue by jvdzwaan** [impactcentre/ocrevalUAtion#13]

**Comment by emolla** [comment]
LICENSE added. 
Thanks!

**Comment by jvdzwaan** [comment]
Thanks for adding a license!

When looking at the code, I saw some files that have a GPL 2.0 license in the header. Also, an older release (1.3.0) has a GPL license (see https://bintray.com/impactocr/maven/ocrevalUAtion). Personally, I prefer Apache, but I wonder if the Apache license is valid in this case. 

Sorry to make such a fuss, the tool is awesome!
