### ISSUE TITLE
Can userProperties.xml be overridden at runtime?

### ISSUE THREAD

**Issue by kba** [impactcentre/ocrevalUAtion#15]
I'm trying to integrate ocrevalUAtion as part of @OCR-D but the predefined `xsi:schemaLocation` lists defined in the properties files would need extending for new versions of PAGE, ALTO etc.

When using the dependency-bundled JAR from bintray, is it possible to replace/extend the properties in `userProperties.xml` at runtime, via command line flag or JVM flag or by placing the file at the right location?

**Comment by cneud** [comment]
IIRC ``userProperties.xml`` can be overridden at runtime by changing the entries in the xml file. 

However, as of cd1a0ae8456565124e3015581f31f2122b0975cd and 055b23b97437d929d4f8dc573e34c436661af76d newer versions of PAGE, ALTO should be supported anyway.

**Comment by cneud** [comment]
> When using the dependency-bundled JAR from bintray, is it possible to replace/extend the properties in `userProperties.xml` at runtime, via command line flag or JVM flag or by placing the file at the right location?

Confirmed - one can change the properties defined in `userProperties.xml` at runtime when the file is in the same directory as the  `ocrevaluation-x-y-z-jar-with-dependencies.jar` downloaded from bintray.
