### ISSUE TITLE
How to get the latest realease ?

### ISSUE THREAD

**Issue by SebastienC-BnF** [impactcentre/ocrevalUAtion#22]
The following link is broken : https://bintray.com/impactocr/maven/ocrevalUAtion
How can I get the latest release, in order to test it ?
Thanks.

**Comment by cneud** [comment]
Dear @SebastienC-BnF, sadly bintray is sunsetting...for convenience, I've now updated the latest release here with a binary https://github.com/impactcentre/ocrevalUAtion/releases/download/v1.3.4/ocrevalUAtion-1.3.4-jar-with-dependencies.jar

**Comment by SebastienC-BnF** [comment]
Many thanks.
